---
title: "Data Science Capstone Project"
author: "Ray Qiu <ray.qiu@gmail.com>"
date: "January 5, 2016"
output: 
  slidy_presentation: 
    keep_md: yes
subtitle: Next Word Prediction
---

## My App

- My App is about predicting the next word based on an input phrase
- Dataset is based on the provided SwiftKey dataset
- Algorithm is about using **pre-computed ngrams** to predict next word of a phrase
- **pre-computed ngrams** includes unigram, bigram, trigram, and quadgram
- One thing to note: Although generally **removing stopwords** is a good idea for text mining, I found that it is **not suitable** for *ngram generation*
- Developed using RStudio Shiny
- Published to shinyapps.io

## UI

- User can select number of predictions using a slider input (default set to 1 per requirement)
- Some simple Help Text is provided to help users understand the usage
- A text input box is provided to input the phrase
- User input is echoed back with leading and trailing whitespaces removed, and word predictions are displayed below the text input box.

## Server

- server.R and predict.R provide the backend
- Echo the input to UI after removing whitespaces
- Load the ngram data (sorted in frequency descending order)
- The prediction algorithm works as follows:
```{r}
predictWord <- function(text, num.predictions) {
  words <- text %>%
           strsplit("\\s+") %>%
           unlist %>%
           removePunctuation %>%
           tolower %>%
           removeNumbers
  # If no input, return unigram results
  if (length(words) == 0) {
    head(unigram$name, n)
  } else if (length(words) == 1) {
    combineWords(processSingle(words, num.predictions))
  } else if (length(words) == 2) {
    combineWords(processDouble(tail(words, 2), num.predictions))
  } else {
    combineWords(processTriple(tail(words, 3), num.predictions))
  }
}
```

- For details of the processXXX and combineWords functions, please see predict.R 

## Where and How to Use the App

- App is hosted at: https://rayqiu.shinyapps.io/next_word_prediction/
- Some Help Text is provided 
- Thanks for your time!
